#Nao tenho limites neste caso...
#enquanto nao acontecer isto, continua no loop...
#estrutura de repeticao com teste logico
#funciona para empre
while True: #em casos de loop infinito podemos apertar o stop para para o programa...
    print('miau')
    break

